name: HTML Validator
on: 
  push:
    paths:
      - '.github/workflows/**'
      - 'source/**.html'
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2      
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: ./source/public
          blacklist: invalid
          CSS: true
