name: Lighthouse
on: [pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Create comment
      id: pr-comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Generating a Lighthouse Report for [https://team-ocean-recipes.netlify.app/](https://team-ocean-recipes.netlify.app/)
          .
          .
          .
    - name: Lighthouse Audit
      id: lighthouse-audit
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: ${{ format('https://deploy-preview-{0}--team-ocean-recipes.netlify.app', github.event.pull_request.number) }}
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        prCommentEnabled: false # toggle this to use foo's default PR comment for audit results
        device: 'desktop'
    - name: Update a comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{steps.pr-comment.outputs.comment-id}}
        body: |
          Report finished!

          ### Lighthouse Audit Results
          Note: Tests ran on desktop device.
          - Accessibility Score: ${{ fromJson(steps.lighthouse-audit.outputs.lighthouseCheckResults).data[0].scores.accessibility }}
          - Best Practices Score: ${{ fromJson(steps.lighthouse-audit.outputs.lighthouseCheckResults).data[0].scores.bestPractices }}
          - Peformance Score: ${{ fromJson(steps.lighthouse-audit.outputs.lighthouseCheckResults).data[0].scores.performance }}
          - Progressive Web App Score: ${{ fromJson(steps.lighthouse-audit.outputs.lighthouseCheckResults).data[0].scores.progressiveWebApp }}
          - SEO Score: ${{ fromJson(steps.lighthouse-audit.outputs.lighthouseCheckResults).data[0].scores.seo }}
