name: linter

on: push

jobs:
  build:
    name: Lint js files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run ESLint
        uses: github/super-linter@v4
        with:
          files: source/public/scripts/
        env:
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
