name: linter

on: push

jobs:
  eslint:
    name: Lint js files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: source/public/scripts/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
