############################################################################### 
# This workflow checks all javascript files that are pushed to ensure that    #
# they are up to ESLint standards. If successful, a green checkmark will      #
# appear in the repository, and if it fails then a red x will be seen. If     #
# the linting check fails, then we can go throught he workflow and see which  # 
# parts of the js files need to be edited.                                    #
###############################################################################

name: linter

# Start job on all pushes
on: push

jobs:
  build:
    name: Lint js files
    runs-on: ubuntu-latest
    # Load all steps
    steps:
      # Checkout code base
      - name: Checkout code
        uses: actions/checkout@v2
      # Run linter against code base
      - name: Run ESLint
        uses: github/super-linter@v4
        env:
          # validate only javascript files
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
