name: Run Unit Tests

on:
    push:
        paths:
            - 'source/__tests__/**.js'
            - 'source/public/**.js'

jobs:
    test:
        name: Jest
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: source
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - run: npm install
            - run: npm test
