name: Run End-to-End Tests

on: [push]

jobs:
    test:
        name: Cypress
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  working-directory: source
